package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nombre")
   private java.lang.String nombre;
   @org.kie.api.definition.type.Label(value = "EstadoContrato")
   private java.lang.String estadoContrato;
   @org.kie.api.definition.type.Label(value = "Rut")
   private java.lang.String rut;
   @org.kie.api.definition.type.Label(value = "NumeroContrato")
   private java.lang.String numeroContrato;
   @org.kie.api.definition.type.Label(value = "Digito")
   private java.lang.String digito;

   public Cliente()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getEstadoContrato()
   {
      return this.estadoContrato;
   }

   public void setEstadoContrato(java.lang.String estadoContrato)
   {
      this.estadoContrato = estadoContrato;
   }

   public java.lang.String getRut()
   {
      return this.rut;
   }

   public void setRut(java.lang.String rut)
   {
      this.rut = rut;
   }

   public java.lang.String getNumeroContrato()
   {
      return this.numeroContrato;
   }

   public void setNumeroContrato(java.lang.String numeroContrato)
   {
      this.numeroContrato = numeroContrato;
   }

   public java.lang.String getDigito()
   {
      return this.digito;
   }

   public void setDigito(java.lang.String digito)
   {
      this.digito = digito;
   }

   public Cliente(java.lang.String nombre, java.lang.String estadoContrato,
         java.lang.String rut, java.lang.String numeroContrato,
         java.lang.String digito)
   {
      this.nombre = nombre;
      this.estadoContrato = estadoContrato;
      this.rut = rut;
      this.numeroContrato = numeroContrato;
      this.digito = digito;
   }

}