package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement(name = "resultado")
public class Respuesta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("success")
   private java.lang.Boolean success;

   @org.kie.api.definition.type.Label("Body")
   private Body body;

   @org.kie.api.definition.type.Label(value = "Status")
   private cl.forum.siniestros.Status status;

   public Respuesta()
   {
   }

   public java.lang.Boolean getSuccess()
   {
      return this.success;
   }

   public void setSuccess(java.lang.Boolean success)
   {
      this.success = success;
   }

   public cl.forum.siniestros.Body getBody()
   {
      return this.body;
   }

   public void setBody(cl.forum.siniestros.Body body)
   {
      this.body = body;
   }

   public cl.forum.siniestros.Status getStatus()
   {
      return this.status;
   }

   public void setStatus(cl.forum.siniestros.Status status)
   {
      this.status = status;
   }

   public Respuesta(java.lang.Boolean success, cl.forum.siniestros.Body body,
         cl.forum.siniestros.Status status)
   {
      this.success = success;
      this.body = body;
      this.status = status;
   }

}