package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Respuesta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "success")
   private java.lang.Boolean success;

   public Respuesta()
   {
   }

   public java.lang.Boolean getSuccess()
   {
      return this.success;
   }

   public void setSuccess(java.lang.Boolean success)
   {
      this.success = success;
   }

   public Respuesta(java.lang.Boolean success)
   {
      this.success = success;
   }

}