package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Seguro implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Seguro() {
    }

}