package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Seguro implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "EstadoSeguto")
   private java.lang.String estadoSeguro;

   @org.kie.api.definition.type.Label(value = "NumeroPoliza")
   private java.lang.String numeroPoliza;

   public Seguro()
   {
   }

   public java.lang.String getEstadoSeguro()
   {
      return this.estadoSeguro;
   }

   public void setEstadoSeguro(java.lang.String estadoSeguro)
   {
      this.estadoSeguro = estadoSeguro;
   }

   public java.lang.String getNumeroPoliza()
   {
      return this.numeroPoliza;
   }

   public void setNumeroPoliza(java.lang.String numeroPoliza)
   {
      this.numeroPoliza = numeroPoliza;
   }

   public Seguro(java.lang.String estadoSeguro, java.lang.String numeroPoliza)
   {
      this.estadoSeguro = estadoSeguro;
      this.numeroPoliza = numeroPoliza;
   }

}