package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Siniestros implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Seguro")
   private cl.forum.siniestros.Seguro seguro;
   @org.kie.api.definition.type.Label("Cliente")
   private cl.forum.siniestros.Cliente cliente;
   @org.kie.api.definition.type.Label("Vechiculo")
   private cl.forum.siniestros.Vehiculo vehiculo;

   @org.kie.api.definition.type.Label(value = "Numero Siniestro")
   private java.lang.String numeroSiniestro;

   @org.kie.api.definition.type.Label(value = "Fecha Ocurrencia")
   private java.util.Date fechaOcurrencia;

   @org.kie.api.definition.type.Label(value = "Monto Indemnizado")
   private java.lang.Long montoIndemnizado;

   @org.kie.api.definition.type.Label(value = "Fecha Pago")
   private java.util.Date fechaPago;

   @org.kie.api.definition.type.Label(value = "Representante Cia")
   private java.lang.String representanteCia;

   @org.kie.api.definition.type.Label(value = "Direccion Cia")
   private java.lang.String direccionCia;

   public Siniestros()
   {
   }

   public cl.forum.siniestros.Seguro getSeguro()
   {
      return this.seguro;
   }

   public void setSeguro(cl.forum.siniestros.Seguro seguro)
   {
      this.seguro = seguro;
   }

   public cl.forum.siniestros.Cliente getCliente()
   {
      return this.cliente;
   }

   public void setCliente(cl.forum.siniestros.Cliente cliente)
   {
      this.cliente = cliente;
   }

   public cl.forum.siniestros.Vehiculo getVehiculo()
   {
      return this.vehiculo;
   }

   public void setVehiculo(cl.forum.siniestros.Vehiculo vehiculo)
   {
      this.vehiculo = vehiculo;
   }

   public java.lang.String getNumeroSiniestro()
   {
      return this.numeroSiniestro;
   }

   public void setNumeroSiniestro(java.lang.String numeroSiniestro)
   {
      this.numeroSiniestro = numeroSiniestro;
   }

   public java.util.Date getFechaOcurrencia()
   {
      return this.fechaOcurrencia;
   }

   public void setFechaOcurrencia(java.util.Date fechaOcurrencia)
   {
      this.fechaOcurrencia = fechaOcurrencia;
   }

   public java.lang.Long getMontoIndemnizado()
   {
      return this.montoIndemnizado;
   }

   public void setMontoIndemnizado(java.lang.Long montoIndemnizado)
   {
      this.montoIndemnizado = montoIndemnizado;
   }

   public java.util.Date getFechaPago()
   {
      return this.fechaPago;
   }

   public void setFechaPago(java.util.Date fechaPago)
   {
      this.fechaPago = fechaPago;
   }

   public java.lang.String getRepresentanteCia()
   {
      return this.representanteCia;
   }

   public void setRepresentanteCia(java.lang.String representanteCia)
   {
      this.representanteCia = representanteCia;
   }

   public java.lang.String getDireccionCia()
   {
      return this.direccionCia;
   }

   public void setDireccionCia(java.lang.String direccionCia)
   {
      this.direccionCia = direccionCia;
   }

   public Siniestros(cl.forum.siniestros.Seguro seguro,
         cl.forum.siniestros.Cliente cliente,
         cl.forum.siniestros.Vehiculo vehiculo,
         java.lang.String numeroSiniestro, java.util.Date fechaOcurrencia,
         java.lang.Long montoIndemnizado, java.util.Date fechaPago,
         java.lang.String representanteCia, java.lang.String direccionCia)
   {
      this.seguro = seguro;
      this.cliente = cliente;
      this.vehiculo = vehiculo;
      this.numeroSiniestro = numeroSiniestro;
      this.fechaOcurrencia = fechaOcurrencia;
      this.montoIndemnizado = montoIndemnizado;
      this.fechaPago = fechaPago;
      this.representanteCia = representanteCia;
      this.direccionCia = direccionCia;
   }

}