package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Siniestros implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Seguro")
   private cl.forum.siniestros.Seguro seguro;
   @org.kie.api.definition.type.Label("Cliente")
   private cl.forum.siniestros.Cliente cliente;
   @org.kie.api.definition.type.Label("Vechiculo")
   private cl.forum.siniestros.Vehiculo vehiculo;

   public Siniestros()
   {
   }

   public cl.forum.siniestros.Seguro getSeguro()
   {
      return this.seguro;
   }

   public void setSeguro(cl.forum.siniestros.Seguro seguro)
   {
      this.seguro = seguro;
   }

   public cl.forum.siniestros.Cliente getCliente()
   {
      return this.cliente;
   }

   public void setCliente(cl.forum.siniestros.Cliente cliente)
   {
      this.cliente = cliente;
   }

   public cl.forum.siniestros.Vehiculo getVehiculo()
   {
      return this.vehiculo;
   }

   public void setVehiculo(cl.forum.siniestros.Vehiculo vehiculo)
   {
      this.vehiculo = vehiculo;
   }

   public Siniestros(cl.forum.siniestros.Seguro seguro,
         cl.forum.siniestros.Cliente cliente,
         cl.forum.siniestros.Vehiculo vehiculo)
   {
      this.seguro = seguro;
      this.cliente = cliente;
      this.vehiculo = vehiculo;
   }

}