package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Solicitud implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Rut Cliente")
   private java.lang.String rutCliente;

   @org.kie.api.definition.type.Label("Aprobacion")
   private java.lang.Boolean aprobacion;

   public Solicitud()
   {
   }

   public java.lang.String getRutCliente()
   {
      return this.rutCliente;
   }

   public void setRutCliente(java.lang.String rutCliente)
   {
      this.rutCliente = rutCliente;
   }

   public java.lang.Boolean getAprobacion()
   {
      return this.aprobacion;
   }

   public void setAprobacion(java.lang.Boolean aprobacion)
   {
      this.aprobacion = aprobacion;
   }

   public Solicitud(java.lang.String rutCliente, java.lang.Boolean aprobacion)
   {
      this.rutCliente = rutCliente;
      this.aprobacion = aprobacion;
   }

}