package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Status implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Code")
   private java.lang.String code;
   @org.kie.api.definition.type.Label(value = "Message")
   private java.lang.String message;

   public Status()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public Status(java.lang.String code, java.lang.String message)
   {
      this.code = code;
      this.message = message;
   }

}