package cl.forum.siniestros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vehiculo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "NombreTipoMarca")
   private java.lang.String nombreTipoMarca;
   @org.kie.api.definition.type.Label(value = "Chasis")
   private java.lang.String chasis;
   @org.kie.api.definition.type.Label(value = "Patente")
   private java.lang.String patente;
   @org.kie.api.definition.type.Label(value = "AnoBien")
   private java.lang.String anoBien;
   @org.kie.api.definition.type.Label(value = "NombreTipoModelo")
   private java.lang.String nombreTipoModelo;

   public Vehiculo()
   {
   }

   public java.lang.String getNombreTipoMarca()
   {
      return this.nombreTipoMarca;
   }

   public void setNombreTipoMarca(java.lang.String nombreTipoMarca)
   {
      this.nombreTipoMarca = nombreTipoMarca;
   }

   public java.lang.String getChasis()
   {
      return this.chasis;
   }

   public void setChasis(java.lang.String chasis)
   {
      this.chasis = chasis;
   }

   public java.lang.String getPatente()
   {
      return this.patente;
   }

   public void setPatente(java.lang.String patente)
   {
      this.patente = patente;
   }

   public java.lang.String getAnoBien()
   {
      return this.anoBien;
   }

   public void setAnoBien(java.lang.String anoBien)
   {
      this.anoBien = anoBien;
   }

   public java.lang.String getNombreTipoModelo()
   {
      return this.nombreTipoModelo;
   }

   public void setNombreTipoModelo(java.lang.String nombreTipoModelo)
   {
      this.nombreTipoModelo = nombreTipoModelo;
   }

   public Vehiculo(java.lang.String nombreTipoMarca, java.lang.String chasis,
         java.lang.String patente, java.lang.String anoBien,
         java.lang.String nombreTipoModelo)
   {
      this.nombreTipoMarca = nombreTipoMarca;
      this.chasis = chasis;
      this.patente = patente;
      this.anoBien = anoBien;
      this.nombreTipoModelo = nombreTipoModelo;
   }

}